/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutAppIndexRouteImport } from './routes/_layout/app/index'
import { Route as LayoutAppTransactionsRouteImport } from './routes/_layout/app/transactions'
import { Route as LayoutAppMetricsRouteImport } from './routes/_layout/app/metrics'
import { Route as LayoutAppHistoryRouteImport } from './routes/_layout/app/history'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAppIndexRoute = LayoutAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppTransactionsRoute = LayoutAppTransactionsRouteImport.update({
  id: '/app/transactions',
  path: '/app/transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppMetricsRoute = LayoutAppMetricsRouteImport.update({
  id: '/app/metrics',
  path: '/app/metrics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppHistoryRoute = LayoutAppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/renew': typeof RenewRoute
  '/terms': typeof TermsRoute
  '/app/history': typeof LayoutAppHistoryRoute
  '/app/metrics': typeof LayoutAppMetricsRoute
  '/app/transactions': typeof LayoutAppTransactionsRoute
  '/app': typeof LayoutAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/renew': typeof RenewRoute
  '/terms': typeof TermsRoute
  '/app/history': typeof LayoutAppHistoryRoute
  '/app/metrics': typeof LayoutAppMetricsRoute
  '/app/transactions': typeof LayoutAppTransactionsRoute
  '/app': typeof LayoutAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/renew': typeof RenewRoute
  '/terms': typeof TermsRoute
  '/_layout/app/history': typeof LayoutAppHistoryRoute
  '/_layout/app/metrics': typeof LayoutAppMetricsRoute
  '/_layout/app/transactions': typeof LayoutAppTransactionsRoute
  '/_layout/app/': typeof LayoutAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/renew'
    | '/terms'
    | '/app/history'
    | '/app/metrics'
    | '/app/transactions'
    | '/app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/renew'
    | '/terms'
    | '/app/history'
    | '/app/metrics'
    | '/app/transactions'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/renew'
    | '/terms'
    | '/_layout/app/history'
    | '/_layout/app/metrics'
    | '/_layout/app/transactions'
    | '/_layout/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  RenewRoute: typeof RenewRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/app/': {
      id: '/_layout/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof LayoutAppIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/transactions': {
      id: '/_layout/app/transactions'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof LayoutAppTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/metrics': {
      id: '/_layout/app/metrics'
      path: '/app/metrics'
      fullPath: '/app/metrics'
      preLoaderRoute: typeof LayoutAppMetricsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/history': {
      id: '/_layout/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof LayoutAppHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAppHistoryRoute: typeof LayoutAppHistoryRoute
  LayoutAppMetricsRoute: typeof LayoutAppMetricsRoute
  LayoutAppTransactionsRoute: typeof LayoutAppTransactionsRoute
  LayoutAppIndexRoute: typeof LayoutAppIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAppHistoryRoute: LayoutAppHistoryRoute,
  LayoutAppMetricsRoute: LayoutAppMetricsRoute,
  LayoutAppTransactionsRoute: LayoutAppTransactionsRoute,
  LayoutAppIndexRoute: LayoutAppIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  RenewRoute: RenewRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
