/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutAppIndexRouteImport } from './routes/_layout/app/index'
import { Route as LayoutAppTransactionsRouteImport } from './routes/_layout/app/transactions'
import { Route as LayoutAppMetricsRouteImport } from './routes/_layout/app/metrics'
import { Route as LayoutAppHistoryRouteImport } from './routes/_layout/app/history'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAppIndexRoute = LayoutAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppTransactionsRoute = LayoutAppTransactionsRouteImport.update({
  id: '/app/transactions',
  path: '/app/transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppMetricsRoute = LayoutAppMetricsRouteImport.update({
  id: '/app/metrics',
  path: '/app/metrics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppHistoryRoute = LayoutAppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/history': typeof LayoutAppHistoryRoute
  '/app/metrics': typeof LayoutAppMetricsRoute
  '/app/transactions': typeof LayoutAppTransactionsRoute
  '/app': typeof LayoutAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/history': typeof LayoutAppHistoryRoute
  '/app/metrics': typeof LayoutAppMetricsRoute
  '/app/transactions': typeof LayoutAppTransactionsRoute
  '/app': typeof LayoutAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/app/history': typeof LayoutAppHistoryRoute
  '/_layout/app/metrics': typeof LayoutAppMetricsRoute
  '/_layout/app/transactions': typeof LayoutAppTransactionsRoute
  '/_layout/app/': typeof LayoutAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/history'
    | '/app/metrics'
    | '/app/transactions'
    | '/app'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/history' | '/app/metrics' | '/app/transactions' | '/app'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/app/history'
    | '/_layout/app/metrics'
    | '/_layout/app/transactions'
    | '/_layout/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/app/': {
      id: '/_layout/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof LayoutAppIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/transactions': {
      id: '/_layout/app/transactions'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof LayoutAppTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/metrics': {
      id: '/_layout/app/metrics'
      path: '/app/metrics'
      fullPath: '/app/metrics'
      preLoaderRoute: typeof LayoutAppMetricsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app/history': {
      id: '/_layout/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof LayoutAppHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAppHistoryRoute: typeof LayoutAppHistoryRoute
  LayoutAppMetricsRoute: typeof LayoutAppMetricsRoute
  LayoutAppTransactionsRoute: typeof LayoutAppTransactionsRoute
  LayoutAppIndexRoute: typeof LayoutAppIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAppHistoryRoute: LayoutAppHistoryRoute,
  LayoutAppMetricsRoute: LayoutAppMetricsRoute,
  LayoutAppTransactionsRoute: LayoutAppTransactionsRoute,
  LayoutAppIndexRoute: LayoutAppIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
